{{ if .Values.enabled }}
{{- if .Values.application_grpc_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-application-grpc-secret
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  application-secret.yaml: |-
{{- toYaml .Values.application_grpc_secret | nindent 4 }}
{{ end }}
{{ end }}