{{ if .Values.developer }}
{{ if not (lookup "v1" "ConfigMap" .Release.Namespace "shared-conf" ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-conf
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  shared.yaml: |-
{{- toYaml .Values.global.shared_conf | nindent 4}}
{{- if not .Values.global.shared_secret.enabled }}
{{- toYaml .Values.global.shared_secret | nindent 4 }}
{{- end }}
